### PR TITLE
Copyediting and recommended edits

### PR DESCRIPTION
**Pull request by opattison**
Don't accept this PR yet unless you're 100% fine with the changes. I might have more edits and so might you. I fixed some small and obvious things and had some recommendations for re-wording as well.

Check out the new "rendered" prose diff view instead of the source diff – it's a [great new feature just added this week on Github](https://github.com/blog/1784-rendered-prose-diffs) and allows for much more careful review of writing changes.

### CODE REVIEW

**Comment by equivalentideas** [comment]
So I should check out the changes, make those edits and then merge. git noob.

**Comment by opattison** [comment]
@equivalentideas Are you asking? Yeah, you could do it that way. I have only done a few PR's and the few projects I run are mostly self-contained right now, so I'm not much help.

**Comment by equivalentideas** [comment]
To the command line! We'll struggle through. Now that it's on http://principles.adactio.com/#organisations can't have typos.

**Comment by equivalentideas** [comment]
Worked this in. Nice work.

**Comment by opattison** [comment]
@equivalentideas Thanks! I'm glad I could help. 

This is exactly the sort of project I would talk about starting but not get anywhere with, so I am glad to make a small contribution. It must be nice to see it on Jeremy's site on day 1.

**Comment by equivalentideas** [comment]
It's crazy. Thanks so much for helping out. I'm very new to git stuff. Your help kicking-off the issues and picking up all the stupid wording stuff makes it way more accessible to people.

I'm trying to get a big range of people involved in this, particularly non-technical types, artists, bureaucrats, professional archivists etc. Clearing up the writing makes a big difference. I'm looking forward to seeing how it plays out.

**Comment by opattison** [comment]
I am definitely behind any push to democratize archiving and data projects. I appreciated your comment about avoiding "broadcast" language – it's very important to get this sort of thing right.

It is interesting to see how GitHub is becoming a tool for more than just programmers and "code" projects now.

**Comment by equivalentideas** [comment]
Yeah definitely. Last year I had a job getting a big academic report up here http://sceptical-climate.investigate.org.au/ hosted with GitHub pages. 

@hugooconnor is doing cool GitHub stuff with his juice business Joostice https://github.com/joostice

**Comment by opattison** [comment]
Those projects look great.

**Pull request merged**
